apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-application-sets
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/NickPaul41/argocd.git
        revision: feature/elk
        directories:
          - path: application-set/*
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/NickPaul41/argocd.git
        targetRevision: feature/elk
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'