apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elk-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: microk8s
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-elk'
    spec:
      project: default
      source:
        repoURL: 'https://charts.bitnami.com/bitnami'
        targetRevision: HEAD
        chart: elk
      destination:
        server: '{{url}}'
        namespace: elk
